# Generated by Django 2.0.1 on 2018-01-23 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('street', models.TextField(verbose_name='Address')),
                ('zip_code',
                 models.CharField(max_length=20, verbose_name='Zip code')),
                ('county',
                 models.CharField(max_length=100, verbose_name='County')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country',
                 models.CharField(max_length=100, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'address',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(help_text='Company name', max_length=255,
                                  verbose_name='Name')),
                ('email',
                 models.EmailField(help_text='E-mail address', max_length=254,
                                   verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Advertiser',
                'verbose_name_plural': 'Advertisers',
                'db_table': 'advertiser',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title',
                 models.CharField(blank=True, max_length=255, null=True,
                                  verbose_name='Title')),
                ('street', models.TextField(verbose_name='Address')),
                ('zip_code',
                 models.CharField(max_length=20, verbose_name='Zip code')),
                ('email',
                 models.EmailField(blank=True, max_length=254, null=True,
                                   verbose_name='E-invoice e-mail')),
                ('tax_office',
                 models.CharField(max_length=100, verbose_name='Tax office')),
                ('tax_number',
                 models.CharField(max_length=50, verbose_name='Tax number')),
                ('county',
                 models.CharField(max_length=100, verbose_name='County')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country',
                 models.CharField(max_length=100, verbose_name='Country')),
                ('advertiser', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='advertisers.Advertiser', verbose_name='Advertiser')),
            ],
            options={
                'verbose_name': 'Billing address',
                'verbose_name_plural': 'Billing addresses',
                'db_table': 'billing_address',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='address',
            name='advertiser',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='advertisers.Advertiser', verbose_name='Advertiser'),
        ),
    ]
