# Generated by Django 2.0.3 on 2018-04-01 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('number',
                 models.CharField(max_length=255, verbose_name='Number')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('style', models.PositiveSmallIntegerField(
                    choices=[(1, 'Left side'), (2, 'Right side'),
                             (3, 'Bipartite side')], db_index=True,
                    verbose_name='Style')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9,
                                                 verbose_name='Latitude')),
                ('longitude',
                 models.DecimalField(decimal_places=6, max_digits=9,
                                     verbose_name='Longitude')),
                ('artery', models.PositiveSmallIntegerField(
                    choices=[(1, 'Main artery'), (2, 'Intermediate artery')],
                    db_index=True, verbose_name='Artery type')),
                ('status', models.BooleanField(db_index=True, default=True,
                                               verbose_name='Is active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Prepared by')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'db_table': 'board',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
